# Generated by Django 3.2.3 on 2021-06-02 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellido_paterno', models.CharField(blank=True, max_length=200)),
                ('apellido_materno', models.CharField(blank=True, max_length=200)),
                ('municipio', models.CharField(max_length=100)),
                ('celular', models.CharField(max_length=30)),
                ('coordinacion', models.CharField(max_length=50)),
                ('invitado_por', models.CharField(max_length=200)),
            ],
        ),
    ]
