# Generated by Django 3.2.3 on 2021-06-02 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='ya_voto',
            field=models.BooleanField(default=False),
        ),
    ]
